import './styles.scss';
import './js/modal';
import './js/btn-menu';
import './js/formMask';
import './js/carousel/carousel';
import './js/btnBackUp';
import './js/carousel/modalSlider';
import './js/carousel/sliderMobile';
import './js/animation/animation';
